CB-123: Edit recipe
knowde-academy/cookbook-fe pull request #10
Opened 2021-08-04 11:30 UTC by KrzysiekLipiec

Form for editing existing recipes with validation (name and content required, maximal length of name: 100)

2021-08-04 12:19 UTC, banaskrzysztof commented on src/app/modules/recipe-edit/containers/recipe-edit-form/recipe-edit-form.component.html
> +      <p class="indent" *ngFor="let item of splitContent; index as i;">{{item}}</p>
```suggestion
      <p class="indent" *ngFor="let item of splitContent">{{item}}</p>
```

2021-08-04 12:21 UTC, banaskrzysztof approved these changes

2021-08-04 12:27 UTC, tomekknowde commented on src/app/modules/recipe-edit/containers/recipe-edit-form/recipe-edit-form.component.ts
> +    this.router.navigate(['/recipes/' + (this.currentId).toString()]);
```suggestion
    this.router.navigate(['/recipes', this.currentId]);
```

2021-08-04 12:27 UTC, tomekknowde commented on src/app/modules/recipe-edit/containers/recipe-edit-form/recipe-edit-form.component.ts
> +    this.router.navigate(['/recipes/' + (this.currentId).toString()]);
```suggestion
    this.router.navigate(['/recipes', this.currentId]);
```

2021-08-04 12:27 UTC, tomekknowde commented on src/app/modules/recipe-edit/containers/recipe-edit-form/recipe-edit-form.component.ts
> +  private loadRecipe(): void {
move private functions below public ones

2021-08-04 12:27 UTC, tomekknowde commented on src/app/modules/recipe-edit/containers/recipe-edit-form/recipe-edit-form.component.ts
> +    this.newRecipe.content = this.newRecipe.content.slice(4, this.newRecipe.content.length - 1);
what we are doing here? please extract these magics to the new function.

2021-08-04 12:27 UTC, tomekknowde commented on src/app/modules/recipe-create/containers/recipe-form/recipe-form.component.ts
> +    this.newRecipe.content = this.newRecipe.content.slice(4, this.newRecipe.content.length - 1);
extract this to the new function

2021-08-05 10:57 UTC, Bopiotr commented on src/app/modules/recipe-create/services/recipe-create.service.ts
> +  url = 'https://cookbook-study-develop.herokuapp.com/api/v1/recipes/';
```suggestion
  readonly url = 'https://cookbook-study-develop.herokuapp.com/api/v1/recipes/';
```

2021-08-05 10:57 UTC, Bopiotr commented on src/app/modules/recipe-edit/services/recipe-edit.service.ts
> +    console.log(recipe);
pls remove `console.log`

2021-08-05 10:57 UTC, Bopiotr commented on src/app/modules/recipe-edit/services/recipe-edit.service.ts
> +    if (error.status === 400) {
you can use switch case for that

2021-08-05 10:57 UTC, Bopiotr commented on src/app/modules/recipe-edit/services/recipe-edit.service.ts
> +@Injectable({
Remove `providedIn: 'root'
```suggestion
@Injectable()
```
and add `providers: [RecipeEditService]` to `RecipeCreateModule`

2021-08-06 09:41 UTC, tomekknowde requested changes

2021-08-06 09:41 UTC, tomekknowde commented on src/app/app-routing.module.ts
> +    loadChildren: () => import('./modules/recipe-list/recipe-list.module').then(m => m.RecipeListModule)
```suggestion
    redirectTo: ''
```

2021-08-06 09:41 UTC, tomekknowde commented on src/app/modules/recipe-form/components/recipe-view/recipe-view.component.ts
> +  @Input() form_name: string[] = ['',''];
split to two @inputs 
```suggestion
  @Input() formName: string = '';
  @Input() actionButtonName: string = '';
```

2021-08-06 09:41 UTC, tomekknowde commented on src/app/modules/recipe-form/components/recipe-view/recipe-view.component.html
> +      <h1>{{form_name[0]}}</h1>
```suggestion
      <h1>{{formName}}</h1>
```

2021-08-06 09:41 UTC, tomekknowde commented on src/app/modules/recipe-form/components/recipe-view/recipe-view.component.html
> +      <button mat-raised-button color="primary" type="submit" class="btn btn-success" [disabled]="!recipeForm.form.valid">{{form_name[1]}}</button>
```suggestion
      <button mat-raised-button color="primary" type="submit" class="btn btn-success" [disabled]="!recipeForm.form.valid">{{actionButtonName}}</button>
```

2021-08-06 09:41 UTC, tomekknowde commented on src/app/modules/recipe-form/components/recipe-view/recipe-view.component.ts
> +export class RecipeViewComponent implements OnInit {
Why `RecipeView`? IMHO `RecipeForm` was a better name for this component.

2021-08-06 09:41 UTC, tomekknowde commented on src/app/modules/recipe-form/components/recipe-view/recipe-view.component.ts
> +  private contentPrep(): string {
always try to use the full name instead of shortcuts.
```suggestion
  private prepareContent(): string {
```

2021-08-06 09:41 UTC, tomekknowde commented on src/app/modules/recipe-form/containers/recipe-create-form/recipe-create-form.component.ts
> +export class RecipeCreateFormComponent {
```suggestion
export class RecipeCreateComponent {
```

2021-08-06 09:41 UTC, tomekknowde commented on src/app/modules/recipe-form/containers/recipe-create-form/recipe-create-form.component.ts
> +  selector: 'app-recipe-form',
```suggestion
  selector: 'recipe-create',
```

2021-08-06 09:41 UTC, tomekknowde commented on src/app/modules/recipe-form/components/recipe-view/recipe-view.component.ts
> +  selector: 'recipe-view',
```suggestion
  selector: 'recipe-form',
```

2021-08-06 09:41 UTC, tomekknowde commented on src/app/modules/recipe-form/components/recipe-view/recipe-view.component.ts
> +  private loadRecipe(): void {
This function should be part of `recipe-edit` component move it to the parent

2021-08-06 09:41 UTC, tomekknowde commented on src/app/modules/recipe-form/models/recipe-create.model.ts
> +export type Emitted = {
we don't need this type at all, please use `Recipe` instead

2021-08-06 09:41 UTC, tomekknowde commented on src/app/modules/recipe-form/components/recipe-view/recipe-view.component.ts
> +  @Output() newRecipeEvent = new EventEmitter<Emitted>();
```suggestion
  @Output() formSubmit = new EventEmitter<Recipe>();
```

2021-08-06 09:41 UTC, tomekknowde commented on src/app/modules/recipe-form/components/recipe-view/recipe-view.component.ts
> +    this.newRecipeEvent.emit({recipe: this.newRecipe, id: this.currentId});
```suggestion
    this.formSubmit .emit({recipe: {...this.recipe, content: content}});
```

2021-08-06 09:41 UTC, tomekknowde commented on src/app/modules/recipe-form/containers/recipe-create-form/recipe-create-form.component.ts
> +  onReceive(emitted: Emitted) {
```suggestion
  createRecipe(recipe: Recipe) {
```

2021-08-06 09:41 UTC, tomekknowde commented on src/app/modules/recipe-form/containers/recipe-create-form/recipe-create-form.component.ts
> +    this.recipeFormService.create(emitted.recipe).subscribe();
```suggestion
    this.recipeFormService.create(recipe).subscribe();
```

2021-08-06 09:41 UTC, tomekknowde commented on src/app/modules/recipe-form/containers/recipe-edit-form/recipe-edit-form.component.html
> +<recipe-view [form_name]="name" (newRecipeEvent)="onReceive($event)"></recipe-view>
```suggestion
<recipe-form formName="Edytuj przepis" actionButtonName="Edytuj" (formSubmit)="editRecipe($event)"></recipe-view>
```

2021-08-06 09:41 UTC, tomekknowde commented on src/app/modules/recipe-form/containers/recipe-edit-form/recipe-edit-form.component.ts
> +export class RecipeEditFormComponent{
```suggestion
export class RecipeEditComponent {
```

2021-08-06 09:41 UTC, tomekknowde commented on src/app/modules/recipe-form/containers/recipe-edit-form/recipe-edit-form.component.ts
> +  selector: 'app-recipe-form',
```suggestion
  selector: 'recipe-edit',
```

2021-08-06 09:41 UTC, tomekknowde commented on src/app/modules/recipe-form/containers/recipe-edit-form/recipe-edit-form.component.ts
> +  onReceive(emitted: Emitted) {
```suggestion
  editRecipe(recipe: Recipe) {
```

2021-08-06 09:41 UTC, tomekknowde commented on src/app/modules/recipe-form/containers/recipe-edit-form/recipe-edit-form.component.ts
> +    if(emitted.id) {
```suggestion
    if(recipe.id) {
```

2021-08-06 09:41 UTC, tomekknowde commented on src/app/modules/recipe-form/containers/recipe-edit-form/recipe-edit-form.component.ts
> +      this.recipeFormService.update(emitted.recipe, emitted.id).subscribe();
```suggestion
      this.recipeFormService.update(recipe).subscribe();
```

2021-08-06 09:41 UTC, tomekknowde commented on src/app/modules/recipe-form/services/recipe-form.service.ts
> +  update(recipe: Recipe, id: number): Observable<Recipe> {
```suggestion
  update(recipe: Recipe): Observable<Recipe> {
```

2021-08-06 09:41 UTC, tomekknowde commented on src/app/modules/recipe-form/services/recipe-form.service.ts
> +    console.log(recipe);
remove all console.log

2021-08-06 09:41 UTC, tomekknowde commented on src/app/modules/recipe-form/services/recipe-form.service.ts
> +    return this.http.patch<Recipe>(this.url + id, recipe)
```suggestion
    return this.http.patch<Recipe>(this.url + recipe.id, recipe)
```

2021-08-06 09:41 UTC, tomekknowde commented on src/app/modules/recipe-form/containers/recipe-create-form/recipe-create-form.component.html
> +<recipe-view [form_name]="name" (newRecipeEvent)="onReceive($event)"></recipe-view>
```suggestion
<recipe-form formName="Nowy przepis" actionButtonName="Dodaj" (formSubmit)="createRecipe($event)"></recipe-view>
```

2021-08-06 09:41 UTC, tomekknowde commented on src/app/modules/recipe-form/components/recipe-view/recipe-view.component.ts
> +  @Input() currentRecipe?: Recipe;
```suggestion
  @Input() recipe?: Recipe;
```

2021-08-06 09:41 UTC, tomekknowde commented on src/app/modules/recipe-form/components/recipe-view/recipe-view.component.ts
> +  newRecipe: Recipe =
move to `recipe-create` form and use `@Input recipe: Recipe`

2021-08-06 09:41 UTC, tomekknowde commented on src/app/modules/recipe-form/components/recipe-view/recipe-view.component.ts
> +    this.newRecipe.content = this.contentPrep();
```suggestion
    const content = this.prepareContent();
```

2021-08-06 09:41 UTC, tomekknowde commented on src/app/modules/recipe-form/components/recipe-view/recipe-view.component.ts
> +    }
use `@Input` and pass information where we should redirect from this component

2021-08-09 08:15 UTC, tomekknowde approved these changes

2021-08-09 08:17 UTC, merged