CB-67-Add-slider
knowde-academy/cookbook-fe pull request #13
Opened 2021-08-06 11:48 UTC by banaskrzysztof

2021-08-06 11:50 UTC, KrzysiekLipiec approved these changes

2021-08-06 12:11 UTC, tomekknowde requested changes

2021-08-06 12:11 UTC, tomekknowde commented on src/app/modules/recipe-list/components/recipe-carousel.component.ts
> +  images = [
use always public
```suggestion
  public limit = 3;
  public images = [
```
or never do that (make your code consistent)
```suggestion
  limit = 3;
  images = [
```

2021-08-06 12:11 UTC, tomekknowde commented on src/app/modules/recipe-list/components/recipe-carousel.component.ts
> +    }
Create enum for screen breakpoints:

```
export enum BreakpointsEnum {
  xs = 576,
  sm = 768,
  md = 992,
  lg = 1200
}
```

```suggestion
    this.limit = event.target.innerWidth < BreakpointsEnum.sm ? 1 : 3;
```

2021-08-06 12:11 UTC, tomekknowde commented on src/app/modules/recipe-list/components/recipe-carousel.component.ts
> +  images = [
images should goes from parent component, change to 
```suggestion
  @Input() images: Array<PleaseCreateProperTypeHere> = [];
```

2021-08-06 12:11 UTC, tomekknowde commented on src/app/modules/recipe-list/components/recipe-carousel.component.ts
> +export class RecipeCarouselComponent {
To be honest, this component don't make big sense, we can just use `<carousel>` inside `recipe-list-component`

2021-08-09 08:12 UTC, tomekknowde approved these changes

2021-08-09 08:13 UTC, merged