CB-38: User can add products to recipes
knowde-academy/cookbook-fe pull request #34
Opened 2021-08-24 09:44 UTC by KrzysiekLipiec

https://team-1626248039387.atlassian.net/jira/software/projects/CB/boards/1?selectedIssue=CB-38

2021-08-31 05:16 UTC, tomekknowde requested changes

2021-08-31 05:16 UTC, tomekknowde commented on src/app/modules/recipe-form/components/products-chips/products-chips.component.ts
> +    });
```suggestion
    this.products = this.allProducts.filter(product => product.amount !== 0);
```

2021-08-31 05:16 UTC, tomekknowde commented on src/app/modules/recipe-form/components/products-chips/products-chips.component.ts
> +    if (value != '') {
```suggestion
    if (value !== '') {
```

2021-08-31 05:16 UTC, tomekknowde commented on src/app/modules/recipe-form/components/products-chips/products-chips.component.ts
> +    if(name != '') {
```suggestion
    if(name !== '') {
```

2021-08-31 05:16 UTC, tomekknowde commented on src/app/modules/recipe-form/components/products-chips/products-chips.component.ts
> +  }
try to avoid nesting ifs
```suggestion
  add(event: MatChipInputEvent): void {
    this.productCountCtrl.setValue(1);
    const value = (event.value || '').trim();

    if (value === '') {
      return;
    }
    if (this.filteredProducts.length === 1) {
      this.filteredProducts[0].amount = 1;
      event.chipInput!.clear();
      this.updateLists();
      return;
    }
    const productCheck = this.allProducts.find(product => product.name === value);
    if (productCheck && productCheck.amount === 0) {
      productCheck.amount = 1;
      event.chipInput!.clear();
      this.updateLists();
    }
  }
```

2021-08-31 05:16 UTC, tomekknowde commented on src/app/modules/recipe-form/components/products-chips/products-chips.component.ts
> +  public onBackspaceKeydown(event: any): void {
no `any`

2021-08-31 05:16 UTC, tomekknowde commented on src/app/modules/recipe-form/components/products-chips/products-chips.component.ts
> +  public onEnterKeydown(event: any): void {
no `any`

2021-08-31 05:16 UTC, tomekknowde commented on src/app/modules/recipe-form/components/products-chips/products-chips.component.ts
> +    const lastCharacter: string = event.data;
```suggestion
  const lastCharacter: string | null = (event as InputEvent).data;
```

2021-08-31 05:16 UTC, tomekknowde commented on src/app/modules/recipe-form/components/products-chips/products-chips.component.ts
> +    }
try to avoid nesting ifs, revert if possible or extract some pieces of code to the smaller functions

2021-08-31 11:43 UTC, banaskrzysztof commented on src/app/modules/recipe-form/components/products-chips/products-chips.component.html
> +                *ngFor="let unit of units; let i = index"
Index is not used

2021-08-31 12:08 UTC, banaskrzysztof approved these changes

2021-09-06 09:08 UTC, tomekknowde approved these changes

2021-09-07 06:55 UTC, merged